[FX-BE]
wecode-bootcamp-korea/24-2nd-FX-backend pull request #1
Opened 2021-09-14 07:38 UTC by jay95ko

Add: Migration file for users

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- models.py 초기셋팅
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- models.py 초기셋팅

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-14 08:48 UTC, lordmyshepherd requested changes

2021-09-14 08:48 UTC, lordmyshepherd commented on contents/models.py
> +    updated_at  = models.DateTimeField(auto_now=True)
```suggestion
    created_at  = models.DateTimeField(auto_now_add=True)
    updated_at  = models.DateTimeField(auto_now=True)
```

이런 반복적인 시간기록 요소를 작성한다면, 매번 선언하기 보다는 아래와 같이 추상화된 class를 만들고 `상속` 받아서 구현해 주세요.

```python
class TimeStampModel(models.Model):
    created_at  = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    class Meta:
        abstract = True

```

만약 다른 앱에 있는 모델 클래스에서도 사용하고 싶다면 `core` app을 생성해서 core.models.py에 클래스 선언뒤 임포트 해주세요.

2021-09-14 08:48 UTC, lordmyshepherd commented on contents/models.py
> +    genre       = models.ManyToManyField("Genre", related_name="contents", blank=True)
ManyToMany colum에 `through` 옵션을 사용해서 중간 테이블을 직접 구현해주세요~

2021-09-14 08:48 UTC, lordmyshepherd commented on users/models.py
> +        return self.name
unique 설정이 안되어 있으면 유저가 중복으로 저장될 수 있지 않을까요?

2021-09-14 08:54 UTC, jay95ko commented on contents/models.py
> +    updated_at  = models.DateTimeField(auto_now=True)
넵 알겠습니다!!

2021-09-14 09:01 UTC, jay95ko commented on contents/models.py
> +    genre       = models.ManyToManyField("Genre", related_name="contents", blank=True)
혹시 따로 중간테이블을 구현하라고 해주신 이유가 있을까요?? 너무나도 간단한 관계인것 같아서요!!

2021-09-15 01:22 UTC, lordmyshepherd commented
LGTM 👍

2021-09-15 01:23 UTC, merged