[고준영] Add: Get WishList
wecode-bootcamp-korea/24-2nd-FX-backend pull request #13
Opened 2021-09-26 06:10 UTC by jay95ko

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 사용자별 wishlist 목록 반환
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 상응하는 wishlist목록이 없다면 빈 배열 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-27 02:56 UTC, lordmyshepherd requested changes

2021-09-27 02:56 UTC, lordmyshepherd commented on wishlists/views.py
> +            "content_id" : wishlist.content.id,
```suggestion
            "user_id"    : wishlist.user.id,
            "content_id" : wishlist.content.id,
```

2021-09-27 07:18 UTC, jay95ko commented
수정 완료하였습니다..!

2021-09-27 09:32 UTC, lordmyshepherd requested changes

2021-09-27 09:32 UTC, lordmyshepherd commented on wishlists/views.py
> +        } for wishlist in wishlists]
wishList column에 이미 user_id를 가지고 있는데 `wishlist.user.id`를 통해서 user_id를 가져오는 것은 불필요한 엑션이 추가되는 것 같습니다. 그 여파로 user table을 JOIN해서 가져와야되는 문제가 발생하네요.

```suggestion
        wishlists =  Wishlist.objects.filter(user=request.user, like = True).select_related('user', 'content')

        result  = [{
            "user_id"    : wishlist.user.id,
            "content_id" : wishlist.content.id,
        } for wishlist in wishlists]
```

2021-09-29 04:39 UTC, jay95ko commented
리뷰 반영하였으며, 반환하는 내용을 조금 변환하였습니다

2021-09-29 06:27 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-09-29 06:27 UTC, merged