Add: added flix signup_type validation
wecode-bootcamp-korea/24-2nd-FX-backend pull request #14
Opened 2021-09-28 01:31 UTC by flow2lime

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- signup_type validation 구현
		 
## 수정 사항들 자세한 내용
- signup_type 을 먼저 분별해서 flix, kakao-login 구분
- 타입마다 요청할 수 있는 요소 구분

## 기타 질문 및 특이 사항 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [X] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [X] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-28 01:50 UTC, lordmyshepherd requested changes
LGT

2021-09-28 01:50 UTC, lordmyshepherd commented on users/views.py
> +                return JsonResponse({'message': 'LOGIN_TYPE_IS_NOT_FLIX'}, status=400)
`flix`를 하드 코딩하는 방법 말고 Enum class를 사용해서 구현해주세요.

```python
from enum import Enum

class SignUpType(Enum):
    FLIX = 1
    KAKAO = 2
```

```suggestion
            if data['signup_type'] != SignUpType.FLIX.name
                return JsonResponse({'message': 'LOGIN_TYPE_IS_NOT_FLIX'}, status=400)
```

2021-09-28 04:41 UTC, flow2lime commented
[Mod] 수정사항을 반영했습니다.
- Enum 라이브러리를 적용했습니다.
- auto() 메서드와 @unique 데코레이터로 중복을 삭제하는 방식을 사용했는데, 그냥 숫자로 1, 2, 3 정의하는 게 나은지 궁금합니다.

2021-09-28 07:31 UTC, lordmyshepherd requested changes

2021-09-28 07:31 UTC, lordmyshepherd commented on users/views.py
> +            GOOGLE = auto()
@unique와 auto()를 사용하신 이유가 있을까요?

```suggestion
        @unique
        class SignUpType(Enum):
            FLIX   = auto()
            KAKAO  = auto()
            GOOGLE = auto()
```

2021-09-28 07:31 UTC, lordmyshepherd commented on users/views.py
> +            GOOGLE = auto()
그리고 해당 클래스는 models.py로 옮겨 주세요~

2021-09-28 16:38 UTC, flow2lime commented on users/views.py
> +            GOOGLE = auto()
1, 2, 3 등 으로 임의의 수를 부여해서 보이게 하는 방법을 처음에 봤을 때, "왜 FLIX 는 1이고, KAKAO 는 2인거지?" 하는 생각이 들었습니다. 구분자를 부여하는거라면 auto() 자동생성 기능으로 혼란을 막고싶었는데... 생각해보면 굳이... 라는 느낌도 있네요. 

뷰 파일에 Enum 클래스를 붙여둔 이유는,
장고 문서에서 Enum 을 모델파일에 사용한 것을 보고 그대로 적용할까 했는데 사용하는 곳이 View 중에서도 Sign-In 부분밖에 없다고 생각했습니다. 그럴 바엔 뷰의 Sign-In 부분에 서브 클래스로 붙여두는 게 직관적일거라 생각했습니다. 다시 돌아보니 다른 방식의 하드코딩이 되어버린 것 같네요.

고쳐서 다시 PR 올리겠습니다!

2021-09-29 08:54 UTC, flow2lime commented on users/views.py
> +                return JsonResponse({'message': 'LOGIN_TYPE_IS_NOT_FLIX'}, status=400)
@lordmyshepherd 
이렇게 enum 으로 변경하는 이유는
데이터베이스에 가벼운 int 값을 넣어서 가볍게 관리하고자 하는 목적,
혹은 통신 자체를 가볍게 하기 위한 목적 
두 가지 정도로 생각할 수 있었는데, 병민님은 어떤 걸 의도하신 건지 궁금합니다. 혹은 완전히 다른 이유였을까요?
모델 자체를 변경해야하나 고민이 되어서 질문드립니다.

2021-09-29 10:21 UTC, flow2lime commented
[Mod] 수정사항을 반영했습니다.
- 기존에 뷰 파일에 있던 Enum 클래스를 모델 파일로 옮겨두었습니다.

장고문서에서 enum 과 비슷하게  활용할 수 있는 IntegerChoices() 라는 필드를 찾았습니다. 
모델을 수정하게 된다면 enum을 대체해서 사용해도 괜찮을까요? (이번 프로젝트에서 진행하겠다는 이야기는 아닙니다 하하)
enum 도 너무 좋지만 제가 보기엔 약간 상위호환 같은 느낌이라서요

2021-09-30 03:03 UTC, lordmyshepherd commented
> IntegerChoices

잘

2021-09-30 03:04 UTC, lordmyshepherd commented
> [Mod] 수정사항을 반영했습니다.
> 
> * 기존에 뷰 파일에 있던 Enum 클래스를 모델 파일로 옮겨두었습니다.
> 
> 장고문서에서 enum 과 비슷하게 활용할 수 있는 IntegerChoices() 라는 필드를 찾았습니다. 모델을 수정하게 된다면 enum을 대체해서 사용해도 괜찮을까요? (이번 프로젝트에서 진행하겠다는 이야기는 아닙니다 하하) enum 도 너무 좋지만 제가 보기엔 약간 상위호환 같은 느낌이라서요

장호님 잘 찾으셨습니다! IntegerChocies()를 사용해서 만들어주세요~

2021-09-30 06:33 UTC, flow2lime commented
[Mod] 수정사항을 반영했습니다.
- signup_type 에 Integerchoice 옵션을 추가해 DB 저장공간을 최적화 했습니다.

2021-09-30 07:50 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-09-30 07:50 UTC, merged