[고준영]Add: Contents List endpoint
wecode-bootcamp-korea/24-2nd-FX-backend pull request #5
Opened 2021-09-15 07:06 UTC by jay95ko

컨텐츠 리스트 반환
리스트 반환 조건 부여
조건 : Ordering, Limit, Category, Nation, Gerne

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Contents List endpoint 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 컨텐츠 리스트 엔드포인트 구현
- 조건부 리스트 반환 구현
- 인기많은 컨텐츠 : wishlist의 숫자를 세어서 Ordering
- Ordering 조건이 없다면 order_by("?") 부여
- 국가, 장르, 카테고리 별 조건 검색 가능

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-15 08:38 UTC, lordmyshepherd requested changes

2021-09-15 08:38 UTC, lordmyshepherd commented on contents/views.py
> +                contents = contents.order_by(ORDER_BY)
filter를 `dictionary comprehension`으로 구현하면 `if/else`로 분기처리 하지 않고 구조적으로 바꿔볼 수 있을 것 같습니다.
고민해보고 적용해보세요~

2021-09-15 08:38 UTC, lordmyshepherd commented on contents/views.py
> +                contents = contents.order_by(ORDER_BY)
힌트는 dictionary를 사용하고 if, else를 사용하지 않도록 구현하는 방법입니다

2021-09-15 08:40 UTC, jay95ko commented on contents/views.py
> +                contents = contents.order_by(ORDER_BY)
넵!!

2021-09-15 09:38 UTC, lordmyshepherd requested changes

2021-09-15 09:38 UTC, lordmyshepherd commented on contents/views.py
> +            if CATEGORIES:
```python
    FILTERS = {
        "CATEGORIES"    : lambda tags: Q(category__in =category_ids),
        "NATION" : lambda regions: Q(nation__in=nations),
    }

    def get(self, request):
        try:
            q = functools.reduce(lambda q1, q2: q1.add(q2, Q.AND), [self.FILTER.get(request.GET[key], Q()) for key in request.GET.keys()])
```

2021-09-15 11:48 UTC, jay95ko commented
알려주신 방향으로 수정 해보았습니다!! 확인 부탁드립니다~!

2021-09-16 01:50 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-09-16 01:50 UTC, merged