[김장호] Add: added basic login view
wecode-bootcamp-korea/24-2nd-FX-backend pull request #6
Opened 2021-09-16 01:32 UTC by flow2lime

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 기본 로그인 POST view 작성
		 
## 수정 사항들 자세한 내용
- 이메일과 비밀번호로 로그인을 하면 토큰을 발행하는 views 파일을 작성했습니다.

## 기타 질문 및 특이 사항
- 프론트와 협업을 위해 간단히 구현해보았습니다. 추후에 Decorator 를 작성할 예정입니다.
- 현재는 kakao login api 작업중입니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [X] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [해당없음 ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-16 01:51 UTC, lordmyshepherd requested changes

2021-09-16 01:51 UTC, lordmyshepherd commented on users/views.py
> +        ALGORITHM     = 'HS256'
ALGORITHM같은 중요한 정보는 my_settings.py로 관리해주세요~

2021-09-16 02:43 UTC, flow2lime commented
수정사항 반영해서 다시 rebase 했습니다. 확인 부탁드립니다.
- AlGORITHM 정보를 my_settings.py 에 별도로 저장된 값으로 변경했습니다.

2021-09-17 01:49 UTC, S2-J1NG commented
기능 구현하고 유닛테스트 작성 한 세트로 진행해주세요!
유닛테스트 내용까지 포함시켜주세요~

2021-09-20 10:33 UTC, flow2lime commented
기본 로그인 관련 사항을 수정하여 반영했습니다. 
- 데코레이터 추가 : 발행한 토큰의 유효기간을 계산하는 로직을 구현했습니다. 'ExpiredSignatureError' 로 예외처리를 해보려고 하는데, 아직 해결하지 못했습니다. 추후 수정 예정입니다.
- 유닛 테스트 케이스 추가 : 회원가입/로그인 테스트 케이스를 작성중입니다. tests.py 에 일부 추가되어있습니다.

2021-09-21 02:56 UTC, jay95ko commented on users/login_decorator.py
> +                payload      = jwt.decode(access_token, SECRET_KEY, algorithms=ALGORITHM)
```python
access_token = request.headers.get('flix_access_token')

if not access_token:
    return JsonResponse({'message': 'KEY_ERROR'}, status=400)

payload = jwt.decode(access_token, SECRET_KEY, algorithms=ALGORITHM)
```
이렇게 변수를 저장해놓는 방식을 어떨까요???
비슷한 로직이기는 하지만 저라면 이렇게 했을것 같은데 장호님의 방식의 이유가 궁금합니다!!

2021-09-21 03:07 UTC, jay95ko commented on users/login_decorator.py
> +                return JsonResponse({'message': 'TOKEN_DOES_NOT_EXIST'}, status=403)
1. 토큰에 있는 유저확인하는 로직
2. 유저가 있다면 wrapping하려고 했던 func를 불러주는 로직
이 보이지 않는것 같습니다!!
혹시 아직 구현중이신건가요?!?!

2021-09-21 03:10 UTC, jay95ko commented on users/tests.py
> +import bcrypt
위로 올라가는게 좋겠죠??ㅎㅎ

2021-09-21 03:10 UTC, jay95ko commented on users/tests.py
> +
필요 없는 공백은 줄여주는게 좋아보입니다!

2021-09-21 06:25 UTC, flow2lime commented on users/login_decorator.py
> +                payload      = jwt.decode(access_token, SECRET_KEY, algorithms=ALGORITHM)
여러 방법으로 시도하던 중이었는데 잘 안되어서요 하하.. 
준영님이 제안해주신 방법이 더 가독성이 좋은 것 같아서 반영해두었습니다.

httpie 와 포스트맨으로 테스트를 진행해봤는데, "flix_access_token" 을 헤더에 잘 넣었는데도 프린트 해보면 읽히지 않는 현상이 있었습니다. 그래서 토큰 유효기간 체크 로직이 잘 동작하는지 확인하지 못했습니다.
혹시 저와 같은 현상을 겪으셨을까요?
![image](https://user-images.githubusercontent.com/62528263/134121600-032bb415-794e-4e43-ac43-db576ab73af2.png)
![image (1)](https://user-images.githubusercontent.com/62528263/134121621-1ee267db-590e-412b-a0aa-33b0057e3c41.png)

2021-09-21 06:26 UTC, flow2lime commented on users/login_decorator.py
> +                return JsonResponse({'message': 'TOKEN_DOES_NOT_EXIST'}, status=403)
예 확인했습니다. 구현해서 다시 PR 올리겠습니다.

2021-09-21 06:37 UTC, flow2lime commented on users/tests.py
> +
일단 연습 단계이기도 하고, 테스트 파일들을 뷰 단위로 분리해서 폴더에 넣어두려합니다. 얼마 작성 안했는데도 너무 길어져서 보기 힘들더라구요.
test_sign_up_view.py, test_sign_in_view.py 등 으로 나누어서 각각 관리해보려고 나누어두었습니다.

1. sign_in 에서 mock 데이터를 발생시키고는 status_code 만 확인하게 두었습니다. 지금은 정상 작동하지만 mock 데이터도 비교하는 로직이 필요한 건 아닌가 생각중입니다.
2. sign_up 에서는 DataError 를 분별하기 위해 transaction.atomic() 이라는 메서드를 활용했습니다. 다른 예외처리의 경우들과는 다르게 database error 에 해당하는 항목은 별도의 transaction 으로 분리해야한다는 설명을 찾기는 했지만 아직 완전히 이해하진 못했습니다.
TranscationTestCase, TransactionManagementError 등의 클래스가 있는 걸 확인했습니다. 추후에 도입해볼 생각입니다.

2021-09-21 06:43 UTC, jay95ko commented on users/login_decorator.py
> +                payload      = jwt.decode(access_token, SECRET_KEY, algorithms=ALGORITHM)
장호님 http통신 규약에서 규정된 헤더만 사용해야 하는 것으로 알고 있습니다!!
원래는 우리가 헤더에 Authorization을 사용 했었죠??
인증 헤더는 http 프로토콜의 헤더에 포함되어 있으나
장호님께서 만들어주신 flix_access_token이라는 것은 헤더에 규정되지 않아 작동하지 않는것 같습니다..!!

2021-09-21 06:46 UTC, jay95ko commented on users/tests.py
> +
장고 test.py에서도 transaction을 신경써야 하나요??궁금궁금!!
제가 테스트 해보았을때는 장고에서는 알아서 트렌젝션이 적용 되는것 으로 알고 있었습니다!!

2021-09-21 07:45 UTC, flow2lime commented on users/login_decorator.py
> +                payload      = jwt.decode(access_token, SECRET_KEY, algorithms=ALGORITHM)
오우 이런 규정이 있는지 몰랐네요. Authorization 으로 테스트/수정해보고 PR 올리도록 하겠습니다. 감사합니다!

2021-09-21 07:48 UTC, flow2lime commented on users/tests.py
> +
네 개별 테스트 케이스 자체는 트랜젝션 구분이 되는 걸 확인했습니다. 유독 DataError 에서만 TransactionManagementError 가 발생해서 이유를 찾는 중인데  이해가 쉽지가 않습니다 하하
혹시나 하니 발생했던 오류 status 코드를 공유드립니다.
![image](https://user-images.githubusercontent.com/62528263/134132194-fb0845bb-78a8-4516-9967-d1b76163c775.png)

2021-09-21 08:16 UTC, flow2lime commented
[Mod] 리뷰 제안 사항을 반영했습니다.
login_decorator : 
- 누락되었던 데코레이터의 유저 ID 반환 부분을 추가했습니다.
- 토큰 유효기간을 체크할 수 있도록 jwt.exceptions.ExpiredSignatureError 를 활용하여 로직을 추가했습니다.
- 테스트를 위해 토큰 유효기간은 1분으로 조정해두었습니다.

/tests : 
- 기존의 tests.py 를 삭제하고 별도의 테스트 폴더를 만들어 유닛 테스트 파일을 옮겨두었습니다.
- 관리와 가독성을 위하여 하나의 파일이던 테스트 파일을 test_sign_up_view.py , test_sign_in_view.py 로 나누어 담아두었습니다.

2021-09-21 08:17 UTC, flow2lime commented on users/login_decorator.py
> +                payload      = jwt.decode(access_token, SECRET_KEY, algorithms=ALGORITHM)
통신 잘 되는 것도 확인했습니다. 감사합니다 준영님!

![image](https://user-images.githubusercontent.com/62528263/134136478-dd2a9aeb-768a-45fd-ac1a-cdfb19fd9391.png)

2021-09-21 11:19 UTC, jay95ko commented on users/login_decorator.py
> +                payload      = jwt.decode(access_token, SECRET_KEY, algorithms=ALGORITHM)
도움이 되었다니 기분이 좋습니다!!!

2021-09-21 11:35 UTC, jay95ko commented on users/tests.py
> +
혹시 해결 하셨는지요 지금 코드를 보니까 어느정도 해결이 된 것 같아보입니다!!
원래는 create를 하는 도중에 error가 발생하여 진행되던 create가 없던 일로 되고 예외처리가 되는 로직인데
test코드에서 또한 create하는 과정에서 transaction이 적용이 되어야 하는데 적용이 되지 않아 발생한 오류 같습니다!!

2021-09-21 11:59 UTC, jay95ko commented on users/tests/test_sign_up_view.py
> +        })
아까 말씀주신 transaction에 관한 에러 발생을 해결한 지점 같아 보입니다.
아마도 response에 담기는 정보에 대해 원자성이 부여가 되어야 하는데 아마도 
client가 post요청을 날리고 응답을 받아오는 과정중 Dataerror가 발생하는 지점에서 rolback이 일어날 것인데 그 rollback이 response에 영향을 주어서?? response자체에 원자성을 부여해주어야 하는것 같습니다..!!

2021-09-21 16:18 UTC, flow2lime commented on users/tests/test_sign_up_view.py
> +        })
네 이 코드가 위에 첨부해두었던 에러메세지를 해결한 코드입니다.
TransactionManagementError 가 transaction 이 깨지고 rollback 되기 전에 DB 쿼리가 실행된다면 발생한다고 하네요. 
발생할 수 있는 케이스가 DB 테이블에 구속조건을 걸어둔 field 들과 상호작용을 할 때인데요. DatabaseError 에 속하는 IntegrityError, DataError 가 대표적이라고 합니다. 다행히도 IntegrityError 는 filter().exists() 체이닝 로직으로 대체하여 방어했지만, DataError 는 try-except 구문상에 노출시켜두었기에 발생했습니다. KeyError 는 DB에 직접 접근하지 않는 예외이기에 무방했구요. 

저도 준영님이 언급해주신 것처럼 DataError가 response에 직접 영향을 주기 때문이라고 생각합니다. 답을 비교하기만 하면 되는 unit test 과정에서는 atomic() 이라는 고립된 작은 공간을 배정해서, 직접 DB field 의 구속조건에 어긋나는 예외를 발생시키기 보단 "예외코드와 메세지가 정상적으로 나온다는 사실" 만을 뽑아낸다고 이해했습니다.

2021-09-22 06:04 UTC, jay95ko commented
더 추가하실 부분 없으면 rebase and merge 해도 무방해보입니다!!

2021-09-22 06:08 UTC, jay95ko commented on users/tests/test_sign_up_view.py
> +        })
네 저랑 비슷하게 이해하신것 같아요!! 비교가 예외를 발생시켜 예외가 같은지 판단하는 것이 아니라 예외 코드과 메세지만을 놓고 평가하는것 이니까요!!

2021-09-22 10:25 UTC, merged