Add : Content Video endpoint 구현중
wecode-bootcamp-korea/24-2nd-FX-backend pull request #7
Opened 2021-09-16 12:19 UTC by jay95ko

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Video Streaming 구현중
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- Video 요청 Range 별 응답 가능

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- Content-Type 에 대해서 공부중인데 어떠한 타입으로 프론트에 넘겨주어야 할지 잘 모르겠습니다...

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-16 12:20 UTC, jay95ko commented
수정을 해야 할 부분이 다량 있을 것 같습니다.
계속 공부중이지만 일단은 데이터 응답이 가능하여 리뷰받기위해 PR올렸습니다!!
FE공부를 조금 해야 할 것 같습니다

2021-09-27 02:54 UTC, lordmyshepherd requested changes

2021-09-27 02:54 UTC, lordmyshepherd commented on config/settings.py
> +    "Range",
👍

2021-09-27 02:54 UTC, lordmyshepherd commented on contents/views.py
> +
아래와 같이 Wrapper Class를 사용해서 구현해보세요. 이렇게 하면 Encapsulation 효과를 볼 수 있습니다.

예를 들어, S3 client를 `boto3`가 아니라 `다른 라이브러리`를 사용하게 됬다고 가정해봅시다. s3_client를 클래스 안에 정의하면 해당 클래스(ContentStreamingView) 자체가 수정이 되어야 합니다. 하지만 외부에서 매개변수로 받아들이면 해당 클래스는 전혀 수정되지 않아도 되고, 단순히 사용자가 새로운 라이브러리를 사용해서 객체를 생성하면 됩니다.

ContentStreamingView 입장에서는 s3_client의 implementation detail을 몰라도 되고, 단순히 주어진 객체를 사용만 하면 되기때문에 s3_client의 implementation이 수정 되었건 말건 전혀 영향을 받지 않습니다. 모듈화가 이루어 진다고 보시면 될것 같습니다.

또한 실제 기능을 가지고 있는 객체를 포장지처럼 한번 더 감싸서, 실제 기능을 담당하는 객체가 변경되도 호출자가 사용하는 함수는 변경이 없도록 하는 효과를 줍니다!

```python
class MyS3Client:
    def __init__(self, s3_client, bucket):
        self.s3_client = s3_client
        self.bucket = bucket
        
    def get_video_file(self, video_path):
        return self.s3_client(Bucket = self.bucket, Key = video_path)
    
boto3_s3 = boto3.client(
      "s3", 
      region_name           = 'ap-northeast-2', 
      aws_access_key_id     =  aws_access_key_id,
      aws_secret_access_key = aws_secret_access_key
)

s3_client = MyS3Client(boto3)

class ContentStreamingView(View):
    def get(self, request, detail_id):
        video = s3_client.get_video(
            Detail.objects.get(id = detail_id).file
        )
        size  = video["ContentLength"]
        ...
    
```

2021-09-28 01:25 UTC, jay95ko commented
수정 완료하였습니다!!

2021-09-28 01:45 UTC, lordmyshepherd requested changes

2021-09-28 01:45 UTC, lordmyshepherd commented on contents/views.py
> +            print(first_byte , last_byte)
프린트 문은 지워주세요~

2021-09-28 01:45 UTC, lordmyshepherd requested changes

2021-09-28 01:45 UTC, lordmyshepherd commented on contents/views.py
> +            length = last_byte - first_byte + 1
줄 바꿈 해주세요~

```suggestion
            last_byte = int(last_byte) if last_byte else size - 1
            
            if last_byte >= size:
                last_byte = size - 1
                
            length = last_byte - first_byte + 1
```

2021-09-28 02:04 UTC, jay95ko commented
수정 했습니다~~!!

2021-09-28 07:29 UTC, lordmyshepherd commented
LGTM 👍

2021-09-28 07:30 UTC, merged